version: '3'

services:
  mysql:
    container_name: teka.local.db
    image: mysql:8.0
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "admin1234"
      MYSQL_DB: "teka"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - "3307:3306"

  redis:
    image: redis:7.0-alpine
    container_name: teka.local.redis
    command: /bin/sh -c "redis-server --requirepass teka"
    ports:
      - "6379:6379"