version: '3'

services:
  mysql:
    container_name: teka.local.db
    image: mysql:8.0
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "teka"
    ports:
      - "3307:3306"

  redis:
    image: redis:7.0-alpine
    container_name: teka.local.redis
    command: /bin/sh -c "redis-server --requirepass teka"
    ports:
      - "6379:6379"